---
- hosts: webservers
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
---
- hosts: loadbalancer
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: ./loadbalancerconfig
        dest: /etc/nginx/sites-available/default.cfg
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes